name: Build iOS IPA (Unsigned)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List project files
      run: ls -l

    # Remova CocoaPods se não usar pods
    - name: Build IPA (Unsigned)
      run: |
        xcodebuild -project Bitchat.xcodeproj \
          -scheme "Bitchat" \
          -configuration Release \
          -archivePath $PWD/build/Bitchat.xcarchive \
          archive

        xcodebuild -exportArchive \
          -archivePath $PWD/build/Bitchat.xcarchive \
          -exportPath $PWD/build/exportedIPA \
          -exportOptionsPlist ExportOptions.plist

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: ipa
        path: build/exportedIPA/*.ipa
